# Use an official node runtime as a parent image
FROM node:15 as builder

ARG ARTIFACTORY_LOGIN

# set working directory
WORKDIR /app


COPY package.json package-lock.json /app/

RUN npm ci
RUN rm -fr .npmrc

COPY . /app/
RUN npm run build

FROM node:15
WORKDIR /app
COPY --from=builder /app/dist /app
COPY --from=builder /app/node_modules /app/node_modules

# Define environment variable
ENV NODE_ENV stage
ENV PORT 3000

EXPOSE 3000

CMD ["node", "--max-http-header-size=16384", "server/app.js"]
