
export let ERROR_CODES = {
  CONFLICT_ERROR: 409,
  BAD_REQUEST_ERROR: 400,
  NOT_FOUND: 404,
  CRITICAL_ERROR: 500
};

export let ERROR_CODES_NAMES = {
  409: 'CONFLICT_ERROR',
  400: 'BAD_REQUEST_ERROR',
  404: 'NOT_FOUND',
  500: 'CRITICAL_ERROR'
};
